# Generated by Django 5.2.3 on 2025-09-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_internship_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='skills',
            field=models.TextField(),
        ),
    ]
